vti_encoding:SR|utf8-nl
vti_author:SR|TANG
vti_modifiedby:SR|TANG
vti_timecreated:TR|16 Oct 2005 09:10:13 -0000
vti_timelastmodified:TR|16 Oct 2005 09:10:13 -0000
vti_cacheddtm:TX|16 Oct 2005 09:10:13 -0000
vti_filesize:IR|2760
vti_cachedlinkinfo:VX|S|bg\\ flowers1.bmp A|<%=Myself%> H|http://ms.ho.net.tw/ H|/Hmath/Rm-ch11/gform.htm
vti_cachedsvcrellinks:VX|FSUS|Hmath/bg\\ flowers1.bmp UAUS|<%=Myself%> NHHS|http://ms.ho.net.tw/ NHUS|file:///Hmath/Rm-ch11/gform.htm
vti_cachedbodystyle:SR|<body background="bg%20flowers1.bmp">
vti_cachedhasbots:BR|false
vti_cachedhastheme:BR|false
vti_cachedhasborder:BR|false
vti_metatags:VR|HTTP-EQUIV=Content-Type text/html;\\ charset=big5 GENERATOR Microsoft\\ FrontPage\\ 4.0
vti_generator:SR|Microsoft FrontPage 4.0
vti_extenderversion:SR|4.0.2.8912
vti_backlinkinfo:VX|
