vti_encoding:SR|utf8-nl
vti_author:SR|TANG
vti_timecreated:TR|24 Aug 2005 03:06:58 -0000
vti_timelastmodified:TR|24 Aug 2005 11:27:27 -0000
vti_filesize:IR|2290
vti_metatags:VR|HTTP-EQUIV=Content-Type text/html;\\ charset=big5 GENERATOR Microsoft\\ FrontPage\\ 4.0
vti_generator:SR|Microsoft FrontPage 4.0
vti_extenderversion:SR|4.0.2.8912
vti_backlinkinfo:VX|hmath/hienter-1.asp
vti_nexttolasttimemodified:TR|24 Aug 2005 10:35:25 -0000
vti_modifiedby:SR|TANG
vti_cacheddtm:TX|24 Aug 2005 11:27:27 -0000
vti_cachedlinkinfo:VX|S|bg\\ flowers1.bmp A|<%=Myself%>
vti_cachedsvcrellinks:VX|FSUS|Hmath/bg\\ flowers1.bmp UAUS|<%=Myself%>
vti_cachedbodystyle:SR|<body background="bg%20flowers1.bmp">
vti_cachedhasbots:BR|false
vti_cachedhastheme:BR|false
vti_cachedhasborder:BR|false
