vti_encoding:SR|utf8-nl
vti_timelastmodified:TR|16 Jun 2011 09:59:30 -0000
vti_extenderversion:SR|4.0.2.8912
vti_filesize:IR|3426
vti_metatags:VR|HTTP-EQUIV=Content-Type text/html;\\ charset=big5 GENERATOR Microsoft\\ FrontPage\\ 4.0
vti_generator:SR|Microsoft FrontPage 4.0
vti_backlinkinfo:VX|
vti_nexttolasttimemodified:TR|16 Jun 2011 09:56:42 -0000
vti_author:SR|TANG
vti_timecreated:TR|26 Aug 2005 00:15:43 -0000
vti_modifiedby:SR|123
vti_cacheddtm:TX|16 Jun 2011 09:59:33 -0000
vti_cachedlinkinfo:VX|S|../hmathw/bg\\ flowers1.bmp A|<%=Myself%> H|http://61.222.248.199/TBKFCSH/TBKFX.htm H|http://61.222.248.199/hsu-fundb/enterr2-1y.asp H|http://ms.ho.net.tw/ H|http://class.ruten.com.tw/user/index00.php H|http://61.222.248.199/Hmath/Rm-ch11/gform.htm H|http://promotion.ezpay.com.tw/c2c/mentoring/what_ezpay/chart02.htm S|http://promotion.ezpay.com.tw/c2c/logo/icon9.gif
vti_cachedsvcrellinks:VX|NSUS|hmathw/bg\\ flowers1.bmp UAUS|<%=Myself%> NHHS|http://61.222.248.199/TBKFCSH/TBKFX.htm NHHS|http://61.222.248.199/hsu-fundb/enterr2-1y.asp NHHS|http://ms.ho.net.tw/ NHHS|http://class.ruten.com.tw/user/index00.php NHHS|http://61.222.248.199/Hmath/Rm-ch11/gform.htm NHHS|http://promotion.ezpay.com.tw/c2c/mentoring/what_ezpay/chart02.htm NSHS|http://promotion.ezpay.com.tw/c2c/logo/icon9.gif
vti_cachedbodystyle:SR|<body background="../hmathw/bg%20flowers1.bmp">
vti_cachedhasbots:BR|false
vti_cachedhastheme:BR|false
vti_cachedhasborder:BR|false
